### ISSUE TITLE
Function request: isLeapYear (with possible solution)

### ISSUE THREAD

**Issue by pfiadDi** [justinmimbs/elm-date-basic#20]
Hi, first: great package - thank you very much for it.
I have this function for determining if a year is a leap year, may you want to integrate it? Can be very useful, for example for date pickers:

```
isLeapYear : Int -> Bool
isLeapYear year =
    case modBy 4 year of
        0 ->
            if String.endsWith "00" (String.fromInt year) then
                case modBy 400 year of
                    0 ->
                        True

                    _ ->
                        False

            else
                True

        _ ->
            False
```

and here the tests for this function:

```
suite : Test
suite =
    describe "A leap year is divisible by 4 when it's not the last year of a century (e.g. 1800) that is not divisible by 400 (e.g. 2000)"
        [ test "2019 is not a leap year" <|
            \_ -> False |> Expect.equal (Date.isLeapYear 2019)
        , test "2020 is a leap year" <|
            \_ -> True |> Expect.equal (Date.isLeapYear 2020)
        , test "2000 is a leap year" <|
            \_ -> True |> Expect.equal (Date.isLeapYear 2000)
        , test "2100 is not a leap year" <|
            \_ -> False |> Expect.equal (Date.isLeapYear 2100)
        ]
```
BR pfiadDi

**Comment by justinmimbs** [comment]
Hi pfiadDi,

Thanks! I'm glad you're enjoying the library.

The library does use an `isLeapYear` function [internally](https://github.com/justinmimbs/date/blob/3.2.0/src/Date.elm#L156-L158), but I haven't exposed it because I've usually found there's another solution with higher-level date functions. [This example](https://github.com/justinmimbs/date/blob/3.2.0/examples/Calendar.elm) might give you another idea for how to use the library for a date picker. If not, then please let me know the specific case you're running into and I'll try to help.

Thanks,

Justin

**Comment by pfiadDi** [comment]
Makes sense that you already have one :) Thx for the example that gives me some inspiration.
