### ISSUE TITLE
Change signature of `now`

### ISSUE THREAD

**Issue by jaredramirez** [justinmimbs/elm-date-basic#29]
Hey there, 

Currently the type signature of `now` is `Task Never Date`. This can cause some problems when chaining this task to other things. For example:
```elm
myOtherTask : Task CustomError MyResult

Date.now
|> Task.andThen myOtherTask
```

This will fail to compile, because `myOtherTask`'s error type is `CustomError` and `now`'s error type is `Never`.

In `elm/time`, this is solved by having the type of `Time.now` be`Task x Posix`. I was able to solve this in my use case by replace `Date.now` with `Task.map2 Date.fromPosix Time.here Time.now`, which is the exact definition of `now` in this package.

I believe this could be fixed by just changing the signature of `now` to be:
```
today : Task x Date
```

This would be a breaking change, but would allow `now` to be used more flexible. Additionally, I don't believe it would break anyone's code when updating as `x` can be inferred to `Never` in any case. What are your thoughts?

**Comment by justinmimbs** [comment]
Hi Jared,

You're right; the error type should be free instead of constrained to `Never`. Luckily, @kofigumbs fixed this in #11, but I never got around to publishing it. It is a breaking change, so I thought I would wait to batch it with more breaking changes. But it's been a long time now, so I finally published 4.0.0 with this fix. 😅 

Thank you both!

Justin
