### ISSUE TITLE
Reuse types from elm/time

### ISSUE THREAD

**Issue by JDemler** [justinmimbs/elm-date-basic#3]
Both `justinmimbs/date` and `elm/time` expose `Weekday` and `Month` with identical semantics.

Seeing that `elm/time` is a core package would it be possible to change this packages interface to use `elm/time` types where available?

Maybe I am missing something obvious here...

**Comment by justinmimbs** [comment]
This is a good question. My intent was to make this package self-contained (it doesn't depend on `elm/time`), so that a user wouldn't have to `import Time` just to use `Month` or `Weekday`. But perhaps I can alias the `Month` and `Weekday` types from `Time` and re-expose them from `Date`, allowing the types to be used interchangeably. I'll take a look at doing this. Thanks!

**Comment by jorgengranseth** [comment]
@justinmimbs that should work - would be really appreciated! Since you already integrate with `elm/time` for tasks it doesn't add any extra indirect dependencies either 👌

**Comment by justinmimbs** [comment]
Thanks for the feedback, Jørgen! I can re-expose the types, but not the constructors, so to express values like `Jan` or `Mon`, a user of this library would need to import `Time`. I was initially ambivalent about this tradeoff, but now I'm thinking it's worth it for the compatibility. I'll publish that in a version 2 soon. :thumbsup:

While I'm at it, I'm probably going to rename `toFormattedString` to just `format` and remove the record conversion functions (`toCalendarDate`, etc.) since they're only for convenience but probably rarely used (I think I only included them for their symmetry with `fromCalendarDate`, etc). Any other renames or removals that you think would be nice, while we're making breaking changes?

Also, when I made the comment above, the package didn't depend on `elm/time`, but, having added `Date.today`, now it does. :grin:

**Comment by JDemler** [comment]
I currently have a file `DateUtils.elm` in my application that implements missing functionality from your old `date-extra` package:

```elm
isBetween : Date -> Date -> Date -> Bool
isBetween lhs rhs x =
    Date.toRataDie lhs <= Date.toRataDie x && Date.toRataDie x <= Date.toRataDie rhs

clamp : Date -> Date -> Date -> Date
clamp minimum maximum date =
    if Date.toRataDie date < Date.toRataDie minimum then
        minimum
    else if Date.toRataDie date > Date.toRataDie maximum then
        maximum
    else
        date

compare : Date -> Date -> Order
compare lhs rhs =
    Basics.compare (Date.toRataDie lhs) (Date.toRataDie rhs)
```

Better than not having them at all, but I think they are really useful to have. 
Just as a datapoint if you are considering readding them :)

Otherwise, I am happy and feel comfortable with the naming!

**Comment by justinmimbs** [comment]
Thanks, Jakob, that's good to know! I will consider adding those again.

I published version 2.0.0 with the changes I mentioned above. Thank you both for the feedback!

**Comment by jorgengranseth** [comment]
For the _record_ 😄 I found `toCalendarDate` useful; it seemed like a clean API for accessing multiple fields at once. But it's easier to add later if found necessary than to remove them, so makes sense to try it when the opportunity presented itself. I'll give it a go without it and let you know if I miss them.

**Comment by justinmimbs** [comment]
Ah! Thanks, Jørgen; again that's good to know. Those were my thoughts too. If you used that pattern more than once, and find it more cumbersome now, please do let me know.

**Comment by jorgengranseth** [comment]
I had used it twice, but I wouldn't say it's much more cumbersome or unreadable without `toCalendarDate`. One case was arguably solved in a better way with `Date.format`, while the other could be replaced by a lambda in a fairly readable manner:
```
    let
        modifiedDate =
            ...
                |> Date.toCalendarDate
    in
    ( modifiedDate.year, modifiedDate.month )
```

```
    ...
        |> (\date -> ( Date.year date, Date.month date ))
```

Formatting wouldn't necessarily work as a solution in other languages than English, but that can be discussed in another issue (#4).

The only other argument I can think of in `toCalendarDate`'s (and its cousins') favour is that that was what made me completely sure that this was the package I was looking for as I skimmed through the docs. I probably would have realised soon after in its current iteration, so again not a big deal.

**Comment by justinmimbs** [comment]
Thanks for sharing!

> that was what made me completely sure that this was the package I was looking for as I skimmed through the docs.

This is very interesting; what was it about those functions? If there's something I can learn from that, then I would love to improve the docs!

**Comment by jorgengranseth** [comment]
I had a look back at the 1.1.0 docs, and I think it's mostly that the record type signatures are much more spacious than the others. So after I have skimmed through a number of nice-to-have sections that were not my main concern at that point, they stand out and make it very clear what I can get back from the `Date` type:

```
toCalendarDate :
    Date
    -> { year : Int
       , month : Month
       , day : Int
       }
```

vs.

```
---
year : Date -> Int

---
quarter : Date -> Int

---
month : Date -> Month

---
monthNumber : Date -> Int

---
ordinalDay : Date -> Int

Extracts the day of the year.

---
day : Date -> Int

Extracts the day of the month.

```

for the same information: "I can retrieve the year, month and day - that's a relief!"

The former is concise and to the point. The latter is a mix-and-match involving mentally parsing type signatures. Although these are all simple signatures, it can't get much clearer than `year : Int`. "Yup, this is what I'm looking for!".

While self-explanatory, I think a single line with an example for each function can help prevent the "wall of text" feeling I get from having only the type annotations, and to show that these functions are actually useful - not API bloat you offer because you can. Ironically I found the record functions helpful in that regard.

To me the `Extractors` (`Destructors` 😄) section would seem natural after the `Constructors`. Could be because I expected to do more manual work than I ended up doing, so my initial thought was "How do I port this data back to my own types/functions?". The `Month and Weekday helpers` were also a relief in this regard.

Similarly, the short `RataDie` section made me realise that
1. You know more about dates than I do, so the package will probably be more thoughtfully designed than helper functions I can quickly hack in place myself.
2. It will be easy to compare dates, regardless of the API you offer for extractions.

--

Another personal opinion on the 2.0.1 docs: The `Month and Weekday` info is important; skimming from the top I see `Month` and `Weekday` without a definition. I would have liked to see something along the lines of
> The `Month` and `Weekday` types used in this package are aliases of `Time.Month` and `Time.Weekday` from `elm/time`. So if you need to express values, like `Jan` or `Thu`, then you'll need to import them from `Time`.

at the top - somewhere around the `type Date` definition. Perhaps a short paragraph at the very top outlining which aspects the package addresses could help prepare me for how to read the docs. It covers quite a lot after all, so it's useful to know that I might not want to skim through the entire thing top to bottom in order to find what I'm looking for.

All of this is anecdotal, of course, so take it with a grain of salt.

**Comment by justinmimbs** [comment]
Awesome! This is great feedback; thank you, Jørgen, for taking the time! I will take another pass at the docs with this in mind. 😄

**Comment by justinmimbs** [comment]
I tried to improve the docs based on this feedback, @jorgengranseth. It was really helpful, so thank you again!

The docs changes are part of [3.0.0](https://package.elm-lang.org/packages/justinmimbs/date/3.0.0/), which gets a major version bump for dropping the exposed `RataDie` module (it also adds `fromPosix`).

**Comment by justinmimbs** [comment]
Hi @JDemler, just to follow up, I added `compare`, `isBetween`, and `clamp` to [3.1.0](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#compare). 👍

**Comment by JDemler** [comment]
Cool, thanks!

**Comment by jorgengranseth** [comment]
Looks great! :tada: Should `clamp` be in the `Rounding` section? :thinking:

**Comment by justinmimbs** [comment]
Thanks! 😃 

I can see how clamping seems similar to rounding in that both can be used to restrict the range of a value. Rounding requires that its input can be approximated (as it may return a new value), whereas clamping only requires that its inputs can be ordered (as it will always return one of them). So I put `clamp` under Ordering since that's the property of dates it relies on. :sweat_smile:
