### ISSUE TITLE
Language support for `format`

### ISSUE THREAD

**Issue by jorgengranseth** [justinmimbs/elm-date-basic#4]
In its current iteration the `format` function formats to English, and that's it. A sensible default, but it may be worth considering a `FormatConfig` type (record alias) that can be easily modified for the format functions needed (such as `ordinalSuffix` and `monthToName`).

I don't desperately need this right now, but figured it would be worth knowing your position on the topic and considering pros and cons with this (and other) approach(es), if this is a problem you want to solve in this package at some point.

Feel free to close the issue when you feel it has been sufficiently explored or if it is not something you want to do.

**Comment by justinmimbs** [comment]
Yes! I would like `format` to support more than just English. Here are some thoughts.

### Current `format`

At the moment `format` adheres to the [date format patterns in UTS #35](https://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns), which allows the following forms for names:

- month: Wide, Abbreviated, Narrow (e.g. January, Jan, J)
- weekday: Wide, Abbreviated, Short, Narrow (e.g. Monday, Mon, Mo, M)

With English, I just truncate the full names to get the shorter names. This leaves the Narrow forms ambiguous (not useful). Also, the template is expressed as a string, which can be convenient, but also seems archaic in a language like Elm.

### Improving `format`

To support more languages, the full and short names need to be defined separately (can't just truncate anymore), so the language config would probably use the [five functions](https://github.com/rluiten/elm-date-extra/blob/master/src/Date/Extra/I18n/I_ja_jp.elm) that `rluiten/elm-date-extra` uses. I think we can live without the Short and Narrow forms.

For formatting `Posix` values, there's [`ryannhg/date-format`](https://github.com/ryannhg/date-format), which uses typed templates (`List Token`) instead of strings. I think this fits nicely with Elm.

So instead of this

```elm
import Date exposing (Date)

formatter : Date -> String
formatter =
    Date.format "MMMM ddd, y"
```

we could have something more like this

```elm
import Date exposing (Date)
import Date.Format
import Date.Language

formatter : Date -> String
formatter =
    Date.formatWithLanguage
        Date.Language.en
        [ Date.Format.monthName
        , Date.Format.text " "
        , Date.Format.dayWithSuffix
        , Date.Format.text ", "
        , Date.Format.year
        ]
```

where `Date.Language` exposes the config type and predefined configs, and `Date.Format` exposes the template fields.

This may be a stretch, but it might be nice if the same language config type was used by both `Date` and `Posix` formatters. This would allow for a separate package of just language configs to exist to be used by both.

```elm
import Time exposing (Posix)
import Posix.Format
import Date.Language

formatter : Time.Zone -> Posix -> String
formatter =
    Posix.Format.formatWithLanguage
        Date.Language.en
        [ Posix.Format.monthName
        , Posix.Format.text " "
        , Posix.Format.dayWithSuffix
        , Posix.Format.text ", "
        , Posix.Format.year
        ]
```

Does that seem too overreaching? Any other thoughts on how to get the most from adding language support in a simple way?

**Comment by jorgengranseth** [comment]
I think there are different needs out there. I personally won't need languages that I don't speak myself, so for me it would be sufficient with a way to override the defaults. But I can imagine predefined configs being useful to some people, and especially if it gives better interop with other popular packages. The five function approach is basically what I had in mind - seems sensible and should work for most use cases.

As for templates vs. tokens, some pros and cons come to mind:

Token functions are interesting, definitely more Elm-like, and probably more sensible since they are type safe - but not necessarily readable. If I'm new to formatting I would have to double check what `monthShort` provides in the same way I'd have to look up what `ddd` gives me, and if I'm used to date formatting I'd probably expect to be able to provide something like a UTS \#35 string.

The connection between token function names and their output is more straightforward, but template strings arguably give a better overview of what the formatted string will look like at a glance. Simple formats are easy in both cases, but I find token lists to be arduous to read with text tokens mixed in. While I'm not convinced that tokens are objectively better, they may be a better fit with what Elm tries to achieve. It's an opinionated language after all.

However, you already have template strings in place. Extending the current system with configs wouldn't be a breaking change (adding `Date.formatWithLanguage`). So I suppose it would be a sensible first step towards "adding language support in a simple way"?

**Comment by justinmimbs** [comment]
I agree, simply adding `Date.formatWithLanguage` should be the first step, which may cover most needs.

Good points above! I appreciate your input. 😄

**Comment by justinmimbs** [comment]
Support for custom languages is now available as [`formatWithLanguage`](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#formatWithLanguage) as discussed above!
