### ISSUE TITLE
Unix timestamp

### ISSUE THREAD

**Issue by lionar** [justinmimbs/elm-date-basic#5]
Is there any possibility right now that i can convert a unix timestamp into a Date type? If not do you plan on adding that functionality?

**Comment by justinmimbs** [comment]
Hi Aron,

Yes, right now it's possible with the help of [`elm/time`](https://package.elm-lang.org/packages/elm/time/latest/Time) to convert a Unix time to a `Date`.

```elm
import Time
import Date exposing (Date)

fromPosix : Time.Zone -> Time.Posix -> Date
fromPosix zone posix =
    Date.fromCalendarDate
        (Time.toYear zone posix)
        (Time.toMonth zone posix)
        (Time.toDay zone posix)
```

You'll need a `Time.Zone` for the conversion as well; here's an example of using `fromPosix`:

```elm
unixTime =
    1536232391

date : Date
date =
    fromPosix
        Time.utc
        (Time.millisToPosix (unixTime * 1000))
```

If you need your Unix time converted to the local date instead of the UTC date, then you'll need to bring in the local `Time.Zone` from elsewhere; [here are some options](https://discourse.elm-lang.org/t/time-zone-explorations/1837).

And if you happen to only need the current local date, then [`Date.today`](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#today) is a task for that.

----

I hope this helps. I've received a few requests for `Posix` conversions, so I will probably add `fromPosix`, as defined above, to the library.

Justin

**Comment by lionar** [comment]
Hi Justin,
That worked!
Thank you for the excellent explanation, very helpful.

Aron

**Comment by justinmimbs** [comment]
You're welcome! Glad that helped.

**Comment by justinmimbs** [comment]
For convenience, `fromPosix` is now in [3.0.0](https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#fromPosix). 😄
